### ISSUE TITLE
Install using wamp 2.4.9

### ISSUE THREAD

**Issue by forjack842** [robots/4dayforecast#2]
Having suffered a PS failure taking out MB & HDD a fresh install needed additional steps. 
Added "Allow from 127.0.0.1" after line "   <Directory "c:/wamp/www/">"
copied getweather.php to index.php in www directory
pulled favicon.ico and testsql.php
added to hosts file
127.0.0.1 	server1.netinfostation.com
127.0.0.1 	server2.netinfostation.com
127.0.0.1 	server3.netinfostation.com
make wamp service autostart with windows startup

**Comment by robots** [comment]
added information into readme.
