### ISSUE TITLE
Little issues

### ISSUE THREAD

**Issue by mati159** [robots/4dayforecast#5]
Hi!
At first, thank you for creating this. I was afraid i'll have to find another weather station, because mine showed me nothing but temperature.

I'm not a programmer, but somehow i've managed to install and configure this software(Google is a blessing). However I don't know if it's my fault, but 'weather.cache' file isn't clearing or removing itself so the weather is not updating. After removing it manually, weather updates so i unlinked the file at the end and it works properly. I don't know it is a right way to do, but it worked for me. I'll be glad if someone with knowledge checked if it's ok what I've done.

I also have some suggestions to help other "end users"
1. In Readme I'll add information how to make wampserver to start automatically during startup (I was wondering why I get "cannot connect to server" prompt)
2. New weather provider has much more places available so for those who uses only one city you could make an option to overwrite the city code with coordinates from google maps (I've done it myself so personally don't need it, but it could help someone)

I don't think I need more support with this software so feel free to ignore this message, but for others it could be useful.

**Comment by robots** [comment]
Hi,
weather.cache is not cleared or deleted, it is just created. The content changes. Its cache for the weather, so the weather is not checked too often from the service provider. This is set to 4 hours currently. If you need to change that:
https://github.com/robots/4dayforecast/blob/a2bc7f472c5c5b5abbe13d2cf6a49ae1d8636cfc/cache.php#L6
this is the line to change (timeout is in hours)

Feel free to create updated readme for this project :-) or put together some information text about changing the city/location. I will add it to the repository documentation.

**Comment by mati159** [comment]
Ok, my bad. Now I know where I made a mistake. I didn't know about timeout so when I started to modify the script there was no response. I thought it works like original one so it updates after start, after pressing 'update forecast' button and after some time (few hours). Thanks for your help and i guess case can be closed.

**Comment by robots** [comment]
good :-) happy to help.
about that documentation: if you have information about what to change for more places open new issue, we will discuss there. this one is closed
