### ISSUE TITLE
4-Day Forecast - .NET Exception - Could not find any recognizable data.

### ISSUE THREAD

**Issue by D3P3CH3CZ** [robots/4dayforecast#7]
Hello, first of all, thanks for this application, it prolonged life cycle of my weather stations already for 2 years :) But it suddenly stopped working, I have this as a web application running on my Synology Apache, weather.cache is being created properly, but 4-Day Forecast application throws exception Could not find any recognizable data - Any idea how to trace this and what could be the issue?

**Comment by gino0631** [comment]
@D3P3CH3CZ can be a duplicate of #8

**Comment by MrBrianG** [comment]
I believe this is related to weatherbit.io only giving 7 days on the free accounts.  I am using a sharper image 5 day forecast and had an error about a week ago.  I was able to modify getweather.php to work around the missing days by duplicating day 7 into day 8 through 10.  Not perfect but it worked.

**Comment by gino0631** [comment]
@MrBrianG yes, you a right

**Comment by D3P3CH3CZ** [comment]
Guys, you are amazing, thanks for helping me, my Evolve meteo station is working back again :)
